# Generated by Django 3.0.2 on 2020-01-17 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airlineid', models.CharField(max_length=256)),
                ('airlineName', models.CharField(max_length=256)),
                ('route', models.CharField(max_length=256)),
                ('airlineComp', models.CharField(max_length=256)),
                ('timedep', models.CharField(max_length=256)),
                ('timearr', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=256)),
                ('price', models.FloatField(max_length=10)),
                ('seats', models.IntegerField(max_length=10)),
                ('route', models.CharField(max_length=256)),
                ('Airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.airline')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnid', models.CharField(max_length=256)),
                ('amount', models.FloatField(max_length=10)),
                ('date', models.CharField(max_length=256)),
                ('droplocation', models.CharField(default='no', max_length=256)),
                ('Airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.airline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
