# Generated by Django 3.0.2 on 2020-01-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='price',
            new_name='Price',
        ),
    ]
