# Generated by Django 3.0.2 on 2020-02-05 06:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0003_auto_20200205_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 6, 58, 14, 759500, tzinfo=utc)),
        ),
    ]
