# Generated by Django 3.0.2 on 2020-01-16 10:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermob',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermob',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 16, 10, 4, 28, 651338, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0, max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnid', models.CharField(max_length=256)),
                ('amount', models.FloatField(max_length=10)),
                ('credit', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 1, 16, 10, 4, 28, 652504, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
