# Generated by Django 3.0.2 on 2020-02-05 06:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0003_auto_20200205_0658'),
        ('cab', '0002_auto_20200116_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermob',
            name='cab',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tax',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 6, 58, 8, 810806, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usermob',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 6, 58, 8, 809798, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='CabOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(max_length=256)),
                ('latitude', models.CharField(max_length=256)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 2, 5, 6, 58, 8, 811402, tzinfo=utc))),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.order')),
            ],
        ),
    ]
