# Generated by Django 3.0.2 on 2020-02-05 07:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0003_auto_20200205_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caborder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 7, 2, 40, 615388, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tax',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 7, 2, 40, 614848, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usermob',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 7, 2, 40, 613868, tzinfo=utc)),
        ),
    ]
