# Generated by Django 3.0.2 on 2020-02-05 09:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0005_auto_20200205_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='caborder',
            name='cab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cab.cabDetail'),
        ),
        migrations.AlterField(
            model_name='cabdetail',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 9, 37, 35, 837278, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caborder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 9, 37, 35, 838993, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tax',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 9, 37, 35, 838247, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usermob',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 9, 37, 35, 836719, tzinfo=utc)),
        ),
    ]
