# Generated by Django 3.0.2 on 2020-02-05 16:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0007_auto_20200205_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='caborder',
            name='amount',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='cabdetail',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 16, 30, 18, 550251, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caborder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 16, 30, 18, 551977, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tax',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 16, 30, 18, 551238, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usermob',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 16, 30, 18, 549690, tzinfo=utc)),
        ),
    ]
